### ISSUE TITLE
E2E functionality tests

### ISSUE THREAD

**Issue by caspiano** [PlaceOS/release#7]
#3 introduces a test suite that can be run as a requirement to merge into nightly.

Perhaps we should have an `unstable` branch that must first pass the integration pipeline before a merge into the `nightly` branch.

**Comment by kimburgess** [comment]
`nightly` is declared as an inherently unstable branch / tag. As image builds are not currently deterministic, I'm unsure about introducing a second `unstable` branch as this implies comparative stability for `nightly`, which is not true. Just because a set of images build and pass platform tests on one day, does not guarantee that the same references will function identically following another build.

Running the suite as part of any PR to nightly definitely make sense though as this should catch some messy human errors with anything involving repo structure changes.

**Comment by kimburgess** [comment]
Adding relevant comment from #9 for inclusion in design of this:
> release is supposed to imprint the state of all placeos libraries every time an update is produced. It would be more appropriate then for shards to reference crystal-client submodule inside release itself for specs and other purposes instead of the remote crystal-client on github (which is the current configuration at the moment in shards.yml).
